--파이널 프로젝트 유저 생성 system 으로 진행
CREATE USER FINAL_ADMIN IDENTIFIED BY FINALPASSWORD;
GRANT CONNECT, RESOURCE TO FINAL_ADMIN;





SELECT * FROM MEMBER_RANK;

INSERT INTO MEMBER_RANK
VALUES(1,'실버',100);

INSERT INTO MEMBER_RANK
VALUES(2,'골드',200);

INSERT INTO MEMBER_RANK
VALUES(3,'플래티넘',300);

INSERT INTO MEMBER_RANK
VALUES(4,'다이아',400);

INSERT INTO MEMBER_RANK
VALUES(0,'노멀',0);

SELECT * FROM MEMBER;
SELECT * FROM member_rank;

INSERT INTO MEMBER(EMAIL, NICKNAME, PASSWORD, GENDER, NAME, BIRTH, CREATED_AT, UPDATED_AT, ADDRESS, ADDRESS_DETAIL, AMOUNT, TX_AMOUNT, LEVEL_NO, STATUS_NO, RANK_NO, PHONE, ADDRESS_DETAIL2)
VALUES('user01@final.com','USER01','password','M','사용자','20210901','20210901','20210901','주소','상세주소',0,0,3,1,1,'010-1234-5678','상세주소2');

INSERT INTO MEMBER
VALUES('user02@final.com','USER02','password','F','사용자2','20210902','20210902','20210902','주소','상세주소',0,0,3,1,0);

SELECT * FROM MEMBER;

SELECT * FROM MESSAGE;

commit;

SELECT * FROM bookmark;
SELECT * FROM AUCTION_TYPE;


SELECT * FROM AUCTION;

INSERT INTO interested_auctions
VALUES(1,3,'USER02');
INSERT INTO BOOKMARK
VALUES(2,4,'USER02');
INSERT INTO BOOKMARK
VALUES(3,5,'USER02');
INSERT INTO BOOKMARK
VALUES(4,6,'USER01');
INSERT INTO BOOKMARK
VALUES(5,7,'USER01');

SELECT * FROM BOOKMARK;
SELECT * FROM interested_auctions;


commit;

